version: '3.9'

services:
  api:
    container_name: clean-auth-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file: ".env"   
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: clean-auth-db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ".env"    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CleanAuth"]
      interval: 5s
      timeout: 5s
      retries: 5          
    
volumes:
  postgres_data: